package com.example.demo.core.model;

public class ColumnStatusDTO {
    private boolean isAutoIncrement;
    private boolean isAutoGenerated;
    private boolean isNullable;
    private boolean isUnique;
    private boolean isPrimaryKey;
    private boolean isForeignKey;

    public ColumnStatusDTO(boolean isAutoIncrement, boolean isAutoGenerated, boolean isNullable, boolean isUnique, boolean isPrimaryKey, boolean isForeignKey) {
        this.isAutoIncrement = isAutoIncrement;
        this.isAutoGenerated = isAutoGenerated;
        this.isNullable = isNullable;
        this.isUnique = isUnique;
        this.isPrimaryKey = isPrimaryKey;
        this.isForeignKey = isForeignKey;
    }

    public boolean isAutoIncrement() {
        return isAutoIncrement;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public boolean isNullable() {
        return isNullable;
    }

    public boolean isUnique() {
        return isUnique;
    }

    public boolean isPrimaryKey() {
        return isPrimaryKey;
    }

    public boolean isForeignKey() {
        return isForeignKey;
    }
}
