package com.example.demo.core.repository;

import com.example.demo.config.DynamicDataSourceConfig;
import com.example.demo.core.annotation.Column;
import com.example.demo.core.annotation.GeneratedValue;
import com.example.demo.core.entity.BaseEntity;
import com.example.demo.core.mapper.AnnotationBasedRowMapper;
import com.example.demo.core.mapper.PagedRowMapper;
import com.example.demo.core.service.GenericService;
import com.example.demo.exception.AppException;
import com.example.demo.helper.DbMetadataHelper;
import org.springframework.jdbc.core.JdbcTemplate;

import java.lang.reflect.Field;
import java.sql.SQLException;
import java.util.*;
import java.util.stream.Collectors;

public abstract class JdbcBaseRepository<T extends BaseEntity> implements JdbcRepository<T> {
    private final DbMetadataHelper dbMetadataHelper;
    private final Class<T> entityClass;
    private final DynamicDataSourceConfig dynamicDataSourceConfig;
    private final GenericService genericService;
    private final String primaryKey;
    private final String tableName;
    private final String dataSource;

    public JdbcBaseRepository(DbMetadataHelper dbMetadataHelper, Class<T> entityClass, DynamicDataSourceConfig dynamicDataSourceConfig, GenericService genericService) {
        this.dbMetadataHelper = dbMetadataHelper;
        this.entityClass = entityClass;
        this.dynamicDataSourceConfig = dynamicDataSourceConfig;
        this.genericService = genericService;
        this.primaryKey = genericService.getPrimaryKey(entityClass);
        this.tableName = genericService.getTableName(entityClass);
        this.dataSource = genericService.getDataSource(entityClass);
    }

    @Override
    public List<T> findAll() {
        List<String> columns = genericService.getColumns(entityClass, true);
        String columnList = String.join(", ", columns);
        String sql = "SELECT " + columnList + " FROM " + tableName + " ORDER BY " + primaryKey;
        return jdbcTemplate().query(sql, new AnnotationBasedRowMapper<>(entityClass));
    }

    @Override
    public List<T> paginate(int page, int limit) {
        List<String> columns = genericService.getColumns(entityClass, true);
        String columnList = String.join(", ", columns);
        String sql = "SELECT " + columnList + " FROM " + tableName + " ORDER BY " + primaryKey;
        return jdbcTemplate().query(sql, new PagedRowMapper<>(new AnnotationBasedRowMapper<>(entityClass), page * limit, limit))
                .stream().filter(Objects::nonNull).toList();
    }

    @Override
    public List<T> paginate(int page, int limit, Map<String, Object> filters) {
        List<String> columns = genericService.getColumns(entityClass, true);
        String columnList = String.join(", ", columns);

        StringBuilder sql = new StringBuilder("SELECT " + columnList + " FROM " + tableName);

        // Build WHERE clause từ filters
        List<Object> params = new ArrayList<>();
        if (filters != null && !filters.isEmpty()) {
            sql.append(" WHERE ");
            sql.append(filters.keySet().stream()
                    .map(key -> key + " = ?")
                    .collect(Collectors.joining(" AND ")));
            params.addAll(filters.values());
        }

        sql.append(" ORDER BY ").append(primaryKey);

        return jdbcTemplate().query(
                sql.toString(),
                params.toArray(),
                new PagedRowMapper<>(new AnnotationBasedRowMapper<>(entityClass), page * limit, limit)
        ).stream().filter(Objects::nonNull).toList();
    }

    @Override
    public int insert(T entity) {
        StringJoiner columns = new StringJoiner(", ");
        StringJoiner placeholders = new StringJoiner(", ");
        List<Object> values = new ArrayList<>();

        try {
            for (Field field : entityClass.getDeclaredFields()) {
                Column colAnno = field.getAnnotation(Column.class);
                if (colAnno == null) {
                    continue;
                }
                boolean isAutoGenerated = field.isAnnotationPresent(GeneratedValue.class);
                if (primaryKey.equalsIgnoreCase(colAnno.name()) && isAutoGenerated) {
                    continue;
                }

                columns.add(colAnno.name());
                placeholders.add("?");
                field.setAccessible(true);
                values.add(field.get(entity));
            }

            String sql = "INSERT INTO " + tableName + " (" + columns + ") VALUES (" + placeholders + ")";
            return jdbcTemplate().update(sql, values.toArray());

        } catch (Exception e) {
            throw new AppException("Error inserting " + tableName, e);
        }
    }

    @Override
    public int update(T entity) {
        StringJoiner setClauses = new StringJoiner(", ");
        try {
            for (Field field : entityClass.getDeclaredFields()) {
                Column colAnno = field.getAnnotation(Column.class);
                if (colAnno != null && !primaryKey.equalsIgnoreCase(colAnno.name())) {
                    setClauses.add(colAnno.name() + " = ?");
                }
            }

            String sql = "UPDATE " + tableName + " SET " + setClauses + " WHERE " + primaryKey + " = ?";
            return jdbcTemplate().update(sql, genericService.getFieldValues(entity, true));

        } catch (Exception e) {
            throw new AppException("Error updating " + tableName, e);
        }
    }

    @Override
    public T findById(Object id) {
        String sql = "SELECT * FROM " + tableName + " WHERE " + primaryKey + " = ?";
        return jdbcTemplate().queryForObject(sql, new AnnotationBasedRowMapper<>(entityClass), id);
    }

    @Override
    public List<T> findByColumn(String columnName, Object value) {
        String sql = "SELECT * FROM " + tableName + " WHERE "  + columnName + " = ?";
        return jdbcTemplate().query(sql, new AnnotationBasedRowMapper<>(entityClass), value);
    }

    @Override
    public List<T> findByColumns(Map<String, Object> conditions) {
        StringBuilder sql = new StringBuilder("SELECT * FROM " + tableName + " WHERE ");
        List<Object> values = new ArrayList<>();

        int i = 0;
        for (Map.Entry<String, Object> entry : conditions.entrySet()) {
            if (i > 0) sql.append(" AND ");
            sql.append(entry.getKey()).append(" = ?");
            values.add(entry.getValue());
            i++;
        }

        return jdbcTemplate().query(sql.toString(), new AnnotationBasedRowMapper<>(entityClass), values.toArray());
    }

    @Override
    public int deleteById(Object id) {
        String sql = "DELETE FROM " + tableName + " WHERE " + primaryKey + " = ?";
        return jdbcTemplate().update(sql, id);
    }

    @Override
    public int deleteByColumn(String columnName, Object value) {
        String sql = "DELETE FROM " + tableName + " WHERE " + columnName + " = ?";
        return jdbcTemplate().update(sql, value);
    }

    @Override
    public int count() {
        String sql = "SELECT COUNT(*) FROM " + tableName;
        try {
            var x = dbMetadataHelper.getColumns(tableName);
            var y = dbMetadataHelper.getPrimaryKeys(tableName);
        } catch (SQLException e) {

        }
        return jdbcTemplate().queryForObject(sql, Integer.class);
    }

    @Override
    public int count(Map<String, Object> filters) {
        StringBuilder sql = new StringBuilder("SELECT COUNT(*) FROM " + tableName);

        List<Object> params = new ArrayList<>();
        if (filters != null && !filters.isEmpty()) {
            sql.append(" WHERE ");
            sql.append(filters.keySet().stream()
                    .map(key -> key + " = ?")
                    .collect(Collectors.joining(" AND ")));
            params.addAll(filters.values());
        }

        return jdbcTemplate().queryForObject(sql.toString(), params.toArray(), Integer.class);
    }


    private JdbcTemplate jdbcTemplate() {
        return dynamicDataSourceConfig.getJdbcTemplate(dataSource);
    }
}
